openapi: 3.0.1
info:
  title: 'STD21029'
  description: Hello world!
  version: 1.0.0
servers:
  - url: https://std21029.com

paths:
  /student: 
    get:
      tags:
        - Student
      summary: Get all students
      operationId: getStudent
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: page_size
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateStudent'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/BadRequest'
    post:
      tags:
        - Student
      summary: Create new students
      operationId: createStudent
      description: Create new students from an array
      requestBody:
        description: Student to be created
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Student'
        required: true
      responses:  
        '200':
            description: List of students
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/CreateStudent'
        '400':
            description: Bad request
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    $ref: '#/components/schemas/BadRequest'
    patch:
      tags:
        - Student
      summary: Update a student
      operationId: UpdateStudent
      description: Update the student with the provided id
      parameters:
        - name: id
          in: query
          schema:
            type: integer
      requestBody:
        description: Informations to update for the student's id
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Student'
        required: true
      responses:  
        '200':
            description: Updated student
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/CreateStudent'
        '400':
            description: Bad request
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    $ref: '#/components/schemas/BadRequest'
        '404':
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RessourceNotFound'
    put:
      tags:
        - Student
      summary: Update all student's informations
      operationId: UpdateAllStudent
      description: Update the whole student 
      parameters:
        - name: id
          in: query
          schema:
            type: integer
      requestBody:
        description: Informations to update
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Student'
        required: true
      responses:  
        '200':
            description: Updated student
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/UpdateStudent'
        '400':
            description: Bad request
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    $ref: '#/components/schemas/BadRequest'
        '404':
            description: Not found
            content:
              application/json:
                schema: 
                  type: array
                  items:
                    $ref: '#/components/schemas/RessourceNotFound'
  /students/{id}:
    get:
      tags: 
        - Student
      summary: Get a student by id
      operationId: getStudentById
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: A student
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateStudent'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/BadRequest'     
    delete:
      tags:
        - Student
      summary: Delete a student by id
      operationId: DeleteStudentById
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Student deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  200:
                    type: string
                    example: Ressource deleted
  /courses: 
    get:
      tags:
        - Courses
      summary: Get all courses
      operationId: getCourse
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: page_size
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/BadRequest'
    post:
      tags:
        - Courses
      summary: Create new course
      operationId: createCourse
      description: Create new students from an array
      requestBody:
        description: Course to be created
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateCourse'
        required: true
      responses:  
        '200':
            description: List of courses
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Course'
        '400':
            description: Bad request
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    $ref: '#/components/schemas/BadRequest'
    patch:
      tags:
        - Courses
      summary: Update a course
      operationId: UpdateCourse
      description: Update the course with the provided id
      parameters:
        - name: id
          in: query
          schema: 
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateCourse'
        required: true
      responses:  
        '200':
            description: Course updated
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Course'
        '400':
            description: Bad request
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    $ref: '#/components/schemas/BadRequest'
        '404':
            description: Not found
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/RessourceNotFound'
    put:
      tags:
        - Courses
      summary: Create new course
      operationId: setCourse
      description: Update all course's informations
      parameters:
        - name: id
          in: query
          schema: 
            type: integer
      requestBody:
        description: Course to update
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateCourse'
        required: true
      responses:  
        '200':
            description: List of courses
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/UpdateCourse'
        '400':
            description: Bad request
            content:
              application/json:
                schema: 
                  type: array
                  items: 
                    $ref: '#/components/schemas/BadRequest'              
  /courses/{id}:
    get:
      tags: 
        - Courses
      summary: Get a course by id
      operationId: getCoursesById
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: A course
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/BadRequest'
    delete:
      tags:
        - Courses
      summary: Delete a course by id
      operationId: DeleteCourseById
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Course deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RessourceDeleted'
                   
components:
  schemas:
    CreateStudent:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: Doe
      xml:
        name: CreateStudent
    Student:
      type: object
      properties:
        name:
          type: string
          example: Doe
      xml:
        name: Student
    UpdateStudent:
      type: object
      properties:
        name:
          type: string
          example: Doe
        id:
          type: integer
          example: 2
      xml:
        name: Student
    CreateCourse:
      type: object
      properties:
        code:
          type: string
          example: PROG1
        name: 
          type: string
          example: Algorithmique
        Teacher:
          type: string
          example: Tokimahey RAMAROZAKA
    Course:
      type: object
      properties:
        id:
          type: integer
          example: 1
        code:
          type: string
          example: PROG1
        name: 
          type: string
          example: Algorithmique
        Teacher:
          type: string
          example: Tokimahery RAMAROZAKA
        CreatedDate:
          type: string
          example: '2022-03-29'
    UpdateCourse:
      type: object
      properties:
        code:
          type: string
          example: PROG1
        name: 
          type: string
          example: Algorithmique
        Teacher:
          type: string
          example: Tokimahery RAMAROZAKA
        id:
          type: integer
          example: 1
    RessourceDeleted:
      type: object
      properties:
        200:
          type: string
          example: Ressource deleted
    BadRequest:
      type: object
      properties:
        400:
          type: string
          example: Bad request   
    RessourceNotFound:
      type: object
      properties:
        404:
          type: string
          example: Ressource not found   
    
        
